name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10


jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

  build_release:
    name: ${{ matrix.os }}-hosted
    needs: create_release
    env:
      buildDir: '${{ github.workspace }}/build'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [386, amd64, arm64, arm]
        exclude:
        - os: macos-latest
          arch: 386
        - os: macos-latest
          arch: arm
    steps:
      - name: Checks-out
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.3'
      - run: make arch-${{ matrix.arch }}
      - name: Compress
        uses: papeloto/action-zip@v1
        with:
          files: build/${{ matrix.arch }}
          dest: luatools-${{ matrix.arch }}-${{ matrix.os }}.zip 
      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./luatools-${{ matrix.arch }}-${{ matrix.os }}.zip
          asset_name: luatools-${{ matrix.arch }}-${{ matrix.os }}.zip
          asset_content_type: application/zip